sdk:
  config:
    base-uri: "https://api.ksef.mf.gov.pl"
    qr-uri: "https://qr.ksef.mf.gov.pl"
    request-timeout: 100
    lighthouse-base-uri: "https://api-latarnia.ksef.mf.gov.pl/"
    default-headers:
      # Wymuszenie formatu Problem Details dla odpowiedzi błędów 400 i 429
      X-Error-Format: "problem-details"
