<?php

declare(strict_types=1);

namespace Poland\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Poland\Domain\Money;
use Poland\Interpretation\InterpretationBoundary;
use Poland\Interpretation\Suggestion;

/**
 * The audit's §10: proof that an interpretation cannot write any figure the
 * deterministic engine owns.
 *
 * One test per named field, because a list in a constant is only a boundary if
 * something fails when it is crossed.
 */
final class EngineBoundaryTest extends TestCase
{
    /** @return list<array{0: string}> */
    public static function engineOwnedFields(): array
    {
        return array_map(
            static fn (string $field): array => [$field],
            InterpretationBoundary::RESERVED_FOR_ENGINE,
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('engineOwnedFields')]
    public function test_ai_cannot_write_an_engine_owned_field(string $field): void
    {
        $this->expectException(\RuntimeException::class);

        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion($field, '9999.99', 1.0, 'read with total confidence', 'ai'),
        ]);
    }

    /** The specific figures the audit names, asserted by name so a rename fails. */
    public function test_the_audit_named_fields_are_all_reserved(): void
    {
        foreach ([
            'zus_total',            // ZUS total
            'pit_due',              // PIT liability
            'vat_due',              // VAT payable
            'vat_surplus',          // VAT surplus
            'tax_base',             // tax base
            'contribution_base',    // contribution base
            'rate',                 // applicable tax rate
            'payment_deadline',     // deadline generated by deterministic rules
            'due_date',
        ] as $field) {
            self::assertTrue(
                InterpretationBoundary::isReserved($field),
                sprintf('"%s" must be reserved for the engine.', $field),
            );
        }
    }

    public function test_a_vat_surplus_cannot_be_read_off_a_letter(): void
    {
        // A surplus is a claim on the tax office. Reading one off a document
        // would create a refund entitlement out of an interpretation.
        $this->expectExceptionMessageMatches('/vat_surplus/');

        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion('vat_surplus', '2600.00', 0.99, 'letter mentions a refund', 'ai'),
        ]);
    }

    public function test_a_deadline_read_from_a_document_cannot_replace_the_computed_one(): void
    {
        // The engine derives deadlines from statute and the working-day
        // calendar. A misread digit on a letter would become the date somebody
        // pays by.
        $this->expectExceptionMessageMatches('/payment_deadline/');

        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion('payment_deadline', '2026-09-30', 0.95, 'printed on the letter', 'ocr'),
        ]);
    }

    public function test_the_same_deadline_recorded_as_evidence_is_allowed(): void
    {
        // "The letter says 30.09" is a fact about the letter and belongs in the
        // record. It simply is not the deadline.
        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion('stated_deadline', '2026-09-30', 0.95, 'printed on the letter', 'ocr'),
        ]);

        $this->addToAssertionCount(1);
    }

    /** @return list<array{0: string}> */
    public static function evidenceFields(): array
    {
        return array_map(
            static fn (string $field): array => [$field],
            InterpretationBoundary::EVIDENCE_FIELDS,
        );
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('evidenceFields')]
    public function test_evidence_fields_are_permitted(string $field): void
    {
        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion($field, 'x', 0.9, 'read from the document', 'ocr'),
        ]);

        $this->addToAssertionCount(1);
    }

    public function test_no_field_is_both_evidence_and_reserved(): void
    {
        // An overlap would make the boundary depend on which check ran first.
        self::assertSame(
            [],
            array_intersect(
                InterpretationBoundary::RESERVED_FOR_ENGINE,
                InterpretationBoundary::EVIDENCE_FIELDS,
            ),
        );
    }

    public function test_one_forbidden_field_among_many_allowed_ones_still_throws(): void
    {
        $this->expectExceptionMessageMatches('/zus_total/');

        InterpretationBoundary::assertNoTaxLiability([
            new Suggestion('authority', 'zus', 0.99, 'x', 'ai'),
            new Suggestion('document_type', 'upomnienie', 0.95, 'x', 'ai'),
            new Suggestion('stated_amount', '2757.34', 0.9, 'x', 'ai'),
            new Suggestion('zus_total', '2757.34', 0.99, 'x', 'ai'),
        ]);
    }

    public function test_disagreement_shows_both_figures_and_favours_neither(): void
    {
        $result = InterpretationBoundary::compare(
            Money::parse('2701.12'),
            Money::parse('2757.34'),
            'ZUS 08/2026',
        );

        self::assertSame('MANUAL REVIEW REQUIRED', $result['verdict']);
        // Both numbers visible, as the audit's example requires. The formatter
        // uses a non-breaking space as the thousands separator.
        $nbsp = "\u{00A0}";
        self::assertStringContainsString('2'.$nbsp.'701,12', $result['detail']);
        self::assertStringContainsString('2'.$nbsp.'757,34', $result['detail']);
        self::assertStringContainsString('56,22', $result['detail'], 'the difference');
        self::assertStringContainsString('ani na korzyść silnika', $result['detail']);
    }

    public function test_a_tolerance_may_absorb_rounding_but_not_a_real_difference(): void
    {
        $withinTolerance = InterpretationBoundary::compare(
            Money::parse('2757.34'),
            Money::parse('2757.35'),
            'ZUS',
            Money::grosze(1),
        );
        self::assertTrue($withinTolerance['agrees']);

        $beyond = InterpretationBoundary::compare(
            Money::parse('2757.34'),
            Money::parse('2757.36'),
            'ZUS',
            Money::grosze(1),
        );
        self::assertFalse($beyond['agrees']);
    }

    public function test_the_engine_being_lower_than_the_document_also_escalates(): void
    {
        // Direction must not matter. Silently accepting the smaller number would
        // underpay; silently accepting the larger would overpay.
        foreach ([['2000.00', '2500.00'], ['2500.00', '2000.00']] as [$engine, $document]) {
            $result = InterpretationBoundary::compare(
                Money::parse($engine),
                Money::parse($document),
                'test',
            );
            self::assertFalse($result['agrees']);
            self::assertSame('MANUAL REVIEW REQUIRED', $result['verdict']);
        }
    }
}
